spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: default
  config:
    additional-location: ./config
  datasource:
    driver-class: org.postgresql.Driver
    url: jdbc:postgresql://analytics.pbl.tec.br:8082/db-micros-discord
    username: micros-discord
    password: 123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl.auto: create
        formatSql: true
    show-sql: true
