spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: default
  config:
    additional-location: ./config
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl.auto: update
        formatSql: true
    show-sql: true

server:
  servlet:
    context-path: /api/discord/integ/